// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIOiM3B5URaz0V8ZnngPMYMpGcL7yRbeo',
    appId: '1:592444539917:web:f033a567dff3e821c10144',
    messagingSenderId: '592444539917',
    projectId: 'chat-app-backend-8357d',
    authDomain: 'chat-app-backend-8357d.firebaseapp.com',
    storageBucket: 'chat-app-backend-8357d.appspot.com',
    measurementId: 'G-MQ8V2P4HM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT9kTJwHhaEffJ_k1ei_spWU73zAoWkmA',
    appId: '1:592444539917:android:8d2c3522cc5f7d0bc10144',
    messagingSenderId: '592444539917',
    projectId: 'chat-app-backend-8357d',
    storageBucket: 'chat-app-backend-8357d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz4dqX_MffOgNIrv4XHuB4FPaFqHjk1l8',
    appId: '1:592444539917:ios:bf1ad6186b09bcafc10144',
    messagingSenderId: '592444539917',
    projectId: 'chat-app-backend-8357d',
    storageBucket: 'chat-app-backend-8357d.appspot.com',
    iosClientId: '592444539917-9p2qs8arr8o1p9vvs2sbrod26qmgrjqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz4dqX_MffOgNIrv4XHuB4FPaFqHjk1l8',
    appId: '1:592444539917:ios:7330f83ab18a9374c10144',
    messagingSenderId: '592444539917',
    projectId: 'chat-app-backend-8357d',
    storageBucket: 'chat-app-backend-8357d.appspot.com',
    iosClientId: '592444539917-39ke5fah4r3j1088bl5hmjtut4ejrl9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
